"""
Mass-Spectrometry File-Converter Service
----------------------------------------
A self-documenting REST micro-service that wraps
ProteoWizard’s msconvert for RAW → mzML conversion,
plus validation, re-conversion and metadata extraction
for the mzML results.

Environment variables are read from `credentials/.env`.
"""
from uu import Error
from flask import  jsonify, request, Response, stream_with_context
from apiflask import APIFlask, Schema, fields
from apiflask.fields import String, File
from apiflask.validators import OneOf
from werkzeug.utils import secure_filename
import os
from functools import lru_cache
from time import sleep
import boto3
from dotenv import load_dotenv
from botocore.exceptions import ClientError, BotoCoreError
import uuid
from flask_cors import CORS
from pathlib import Path
from typing import BinaryIO, Union
import requests
import datetime
import pytz
import json
from mzml_metadataextractor.mzml_metadata_extraction import extract_metadata
import shutil


# Initial + Runtime Configurations

main_path = os.getcwd()
working_dir = os.path.join(main_path, "input_files")

MAX_FILE_SIZE = 10 * 1024 * 1024 * 1024     #10GB
CHUNK = 16 * 1024 * 1024                    #16MB
INPUT_DIR = Path("input_files")
INPUT_DIR.mkdir(exist_ok=True)

# Flask / APIFlask Configuration

app = APIFlask(__name__, title='Mass Spectrometry (MS) File Converter', version='1.0', docs_path='/api')
CORS(app)

CREDENTIALS = os.path.join(main_path, "credentials/.env")
load_dotenv(CREDENTIALS)


#  OpenAPI metadata

app.config['DESCRIPTION'] = "The objective is to convert MS file into mzML"
app.config['EXTERNAL_DOCS'] = {
    'description': "NFDI4Chem",
    'url': 'https://www.nfdi4chem.de/'
}

app.config['TERMS_OF_SERVICE'] = 'https://webconverter.nfdi4chem.zih.tu-dresden.de/privacy_policy'
app.config['LICENSE'] = {
    'name': 'MIT',
    'url': 'https://opensource.org/licenses/MIT'
}

app.config['TAGS'] = [
    {'name': 'msconvert:Conversion',
     'description': 'The aim of conversion is to convert a format to a standardized/agreed format'},
    {'name': 'FileInfo:Validation',
     'description': 'The goal of validation is to Validate the converted format converted by converter service.'},
    {'name': 'FileConvert:Conversion',
     'description': 'The aim of conversion is to test the mzML file'},
    {'name': 'FileMetadata:MetadataExtraction',
     'description': 'The aim of extract metadata from the mzML file'},
]

app.config['IMAGE_FOLDER'] = 'input_files'

# Request / Response Schemas

class Files_convert(Schema):
    main_file = File(
        required=True,
        metadata={'title': 'The path of the input file (in this case RAW file)',
                  'description': 'The objective is to convert the RAW file to mzML file using Proteowizard-->'
                                 'msconvert software'}
    )
    parameters = String(
        required=False,
        metadata={'title': 'This is for additional parameter that could be added for conversion',
                  'description': 'Additional parameter that can modify the outputs'}
    )
    


class Files_validate(Schema):
    validation_file = File(
        required=False,
        metadata={'title': 'The path of the intermediate file or "validate.yml" file generated by the converter service',
                  'description': 'The path of the intermediate yml file is given'}
    )
   

class Filesconverter(Schema):
    main_file = File(
        required=True,
        metadata={'title': 'The path of the input file (in this case mzML file)',
                  'description': 'The objective is to test the mzML file to FileConvert'}
    )


class FileMetadata(Schema):
    main_file = File(
        required=True,
        metadata={'title': 'The path of the input file (in this case mzML file)',
                  'description': 'The objective is to extract metadata from the mzML.'}
    )
    include_parameter = String(
        required=True,
        validate=OneOf(['none', 'with spectra', 'with chromatogram', 'with spectra+chromatogram']),
        metadata={'description': 'Extra data to attach'}
    )

# ------------------------------------------------------------------
# Re-usable S3 client
# ------------------------------------------------------------------
@lru_cache(maxsize=1)
def get_s3_client() -> boto3.client:
    """Return a boto3 S3 client configured for Ceph."""
    try:
        return boto3.client(
            "s3",
            endpoint_url=os.getenv("ENDPOINT_URL"),
            aws_access_key_id=os.getenv("ACCESS_KEY"),
            aws_secret_access_key=os.getenv("SECRET_KEY"),
            region_name="",  # Ceph does not use AWS regions
        )
    except KeyError as e:  # noqa: BLE001
        raise RuntimeError(f"Missing S3 credential: {e}") from None
    except (BotoCoreError, ClientError) as e:
        raise RuntimeError(f"Cannot create s3 client: {e}") from e



# ------------------------------------------------------------------
# Upload helpers
# ------------------------------------------------------------------
def generate_presigned_put_url(
    key: str,
    *,
    expires_in: int = 3_600,
) -> str:
    """Return a one-off PUT URL for the given object key."""
    s3 = get_s3_client()
    bucket = os.getenv("BUCKET")
    try:
        return s3.generate_presigned_url(
            "put_object",
            Params={"Bucket": bucket, "Key": key},
            ExpiresIn=expires_in,
        )
    except (BotoCoreError, ClientError) as exc:
        raise RuntimeError("Could not create pre-signed URL") from exc


#  Helpers – cloud / S3 interaction

def upload_via_presigned_url(
    url: str,
    file_handle: BinaryIO,
    *,
    chunk_size: int = 16 * 1024 * 1024,
) -> None:
    """Stream *file_handle* to *url* using HTTP PUT."""
    resp = requests.put(
        url, 
        data=file_handle, 
        headers={"Content-Type": "application/octet-stream"},
        timeout=None
        )
    if resp.status_code != 200:
        raise RuntimeError(
            f"Upload failed: HTTP {resp.status_code} – {resp.text}"
        )



# ------------------------------------------------------------------
# Convenience wrapper
# ------------------------------------------------------------------
def upload_fileobj(
    file_handle: BinaryIO,
    filename: str,
    file_id: str,
) -> None:
    """Upload *file_handle* under 'nfdi4chemCSFlask/{file_id}/{filename}'."""
    current = file_handle.seek(0, os.SEEK_END)          # go to EOF
    if current > MAX_FILE_SIZE:
        current_gb = current / (1024 ** 3)
        max_gb = MAX_FILE_SIZE / (1024 ** 3)
        raise ValueError(
            f"{filename} is {current_gb:.2f} GB – "
            f"maximum allowed is {max_gb:.0f} GB"
        )
    file_handle.seek(0)
    bucket = os.getenv("BUCKET")
    key = f"{file_id}/{filename}"
    url = generate_presigned_put_url(key)
    print(f"Upload link: {url}")
    upload_via_presigned_url(url, file_handle)
    print(f"✔ {filename} uploaded to {key}")
    return



# generates a UUID for an input
def foldername():
    return str(uuid.uuid4())[:8]



# cleans up the s3 bucket : objects older than 1 hour
def cleanup() -> None:
    s3 = get_s3_client()
    bucket = os.getenv('BUCKET')
    if not bucket:
        print("BUCKET environment variable not set properly.")
        return

    cutoff = datetime.datetime.now(pytz.UTC) - datetime.timedelta(hours=1)

    paginator = s3.get_paginator('list_objects_v2')
    deleted = 0
    try:
        for page in paginator.paginate(Bucket=bucket):
            for obj in page.get('Contents', []):
                if obj['LastModified'] < cutoff:
                    key = obj['Key']
                    print(f"Deleting {key} (Last Modified: {obj['LastModified']})")
                    s3.delete_object(Bucket=bucket, Key=key)
                    deleted += 1
    except (ClientError, BotoCoreError) as e:
        print(f" Error listing objects in bucket {bucket}: {e}")

    print(f"Cleanup finished. Deleted {deleted} objects.")
    print("-----------------------------------")




# Generates a download link to download file
def download_file(filename, file_id):
    s3 = get_s3_client()
    data_key = file_id+ '/' +filename
    response = s3.generate_presigned_url('get_object',
                                         Params={'Bucket': os.getenv('BUCKET'), 'Key': data_key}
                                         )
    
    print("--------------------------------------")
    print("Download Link")
    print(response)
    print("--------------------------------------")
    #content = requests.get(response)
    return response



def fetch_file(url: str, filename:str, folder_id:str):
    """
    Downloads *url* to  INPUT_DIR / folder_id / filename
    and returns the Path object (guaranteed to exist).
    """
    target_dir = INPUT_DIR / folder_id
    target_dir.mkdir(parents=True, exist_ok=True)

    path = target_dir / Path(filename).name

    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(path, "wb") as f:
            for chunk in r.iter_content(chunk_size=CHUNK):
                if chunk:
                    f.write(chunk)
    return path


# remove the entire component of the folder (including the folder)

def remove_folder(abs_path: Union[str, Path]) -> None:
    path = Path(abs_path)

    if not path.is_absolute():
        raise ValueError("Path must be absolute – got: {}".format(path))

    if not path.exists():
        raise FileNotFoundError(f"No such file or directory: {path}")
    if not path.is_dir():
        raise NotADirectoryError(f"Not a directory: {path}")

    shutil.rmtree(path)


# Conversion into mzML data
@app.route("/convert/msconvert", methods=["POST"])
@app.input(Files_convert, location='form_and_files')
#@app.output(MSConvertOut)
@app.doc(tags=['msconvert:Conversion'])
def msfile_conversion(form_and_files_data):
    uploaded_file = form_and_files_data["main_file"]
    if not uploaded_file.filename:
        return jsonify({'Error Type: Empty File Name Found'}) , 400

    file_id = foldername()
    filename = secure_filename(uploaded_file.filename)

    config_parameters = form_and_files_data["parameters"]

    cleanup()
    try:
        upload_fileobj(uploaded_file, filename, file_id)
    except ClientError as e:
        return jsonify({'Error Type': str(e)}) , 500

    try:
        download_url = download_file(filename=filename, file_id=file_id)
    except (ClientError,BotoCoreError) as e:
        return jsonify({'Error Type': str(e)}) , 500
    
    try:
        #if filename.endswith('.tar') or filename.lower().endswith('raw'):
        if filename.lower().endswith(('.tar', '.tar.gz' ,'.tar.xz', '.raw')):
            request1= requests.post(url="http://nfdi4chem-ms-msconvert:4000/msconvert_file",
            json={
                'filename': filename,
                'download_url': download_url,
                'foldername': file_id,
                'config': config_parameters
            })
            request1.raise_for_status()
            print(request1.json())
            mzml_name = request1.json()["mzml_outputfile_name"]
            payload = {
                "status": "success",
                "file_info": {
                    "filename": mzml_name,
                    "download_url": request1.json().get("mzml_download_url"),
                    "valid_for": "1 hour"
                },
                "meta": {
                    "message": f"Converted File - '{mzml_name}' is ready for download.",
                    "timestamp": datetime.datetime.now(pytz.timezone("Europe/Berlin")).isoformat(),
                    "http_status": request1.status_code
                }
            }
            return Response(
                json.dumps(payload, indent=2, ensure_ascii=False),
                mimetype="application/json"
            ), 200
        else:
            return jsonify({"error": "Invalid file type"}), 400   
    except Exception as e:
        return jsonify({'Error_type': str(e)}), 500


    
# Validation of the mzml data

@app.route("/validate/fileinfo", methods=["POST"])
@app.input(Files_validate, location='form_and_files')
#@app.output(FileInfoOut)
@app.doc(tags=['FileInfo:Validation'])
def validation_result(form_and_files_data):
    uploaded_file = form_and_files_data["validation_file"]

    if not uploaded_file.filename:
        return jsonify({'Error Type: Empty File Name Found'}) , 400

    file_id = foldername()
    filename = secure_filename(uploaded_file.filename)

    # FileStorage is already a BinaryIO object; just hand it over.
    # upload_fileobj streams via requests.put, so memory stays low.
    cleanup()

    try:
        upload_fileobj(uploaded_file, filename, file_id)
    except ClientError as e:
        return jsonify({'Error Type': str(e)}) , 500

    try:
        download_url = download_file(filename=filename, file_id=file_id)
    except (ClientError,BotoCoreError) as e:
        return jsonify({'Error Type': str(e)}) , 500
    
    try:
        if filename.lower().endswith('mzml'):
            request1= requests.post(url="http://nfdi4chem-ms-validation:3000/fileinfo_mzml",
            json={
                'filename': filename,
                'download_url': download_url,
                'foldername': file_id
            })
            request1.raise_for_status()
            payload = {
                "status": "success",
                "file_info": {
                    "filename": filename
                },
                "meta": {
                    "message": request1.json().get("output_message"),
                    "timestamp": datetime.datetime.now(pytz.timezone("Europe/Berlin")).isoformat(),
                    "http_status": request1.status_code
                }
            }
            return Response(
                json.dumps(payload, indent=2, ensure_ascii=False),
                mimetype="application/json"
            ), 200

        else:
            return jsonify({'error': "Error incurred due to File format"}), 500
    except Error as e:
        return jsonify({'error': str(e)}), 500


# Convert + validation of mzml data

@app.route("/convert/fileconvert", methods=["POST"])
@app.input(Filesconverter, location='form_and_files')
@app.doc(tags=['FileConvert:Conversion'])
def fileconvert(form_and_files_data):
    uploaded_file = form_and_files_data["main_file"]
    if not uploaded_file.filename:
        return jsonify(error="empty filename"), 400

    file_id = foldername()
    filename = secure_filename(uploaded_file.filename)


    # FileStorage is already a BinaryIO object; just hand it over.
    # upload_fileobj streams via requests.put, so memory stays low.
    cleanup()
    try:
        upload_fileobj(uploaded_file, filename, file_id)
    except ClientError as e:
        return jsonify({'Error Type': str(e)}) , 500

    try:
        download_url = download_file(filename=filename, file_id=file_id)
    except (ClientError,BotoCoreError) as e:
        return jsonify({'Error Type': str(e)}) , 500 
    
    try:
        if filename.lower().endswith('mzml'):
            request1= requests.post(url="http://nfdi4chem-ms-validation:3000/fileconvert_mzml",
            json={
                'filename': filename,
                'download_url': download_url,
                'foldername': file_id
            })
            request1.raise_for_status()
            payload = {
                "status": "success",
                "process": request1.json().get("message"),
                "file_info": {
                    "filename": request1.json().get("fileconvert_filename"),
                    "download_url": request1.json().get("mzml_fileconvert_download_link"),
                    "valid_for": "1 hour"
                },
                "meta": {
                    "message": request1.json().get("Validation_message"),
                    "timestamp": datetime.datetime.now(pytz.timezone("Europe/Berlin")).isoformat(),
                    "http_status": request1.status_code
                }
            }
            return Response(
                json.dumps(payload, indent=2, ensure_ascii=False),
                mimetype="application/json"
            ), 200
        else:
            return jsonify({'error': "Error incurred due to File format"}), 500
    except Error as e:
        return jsonify({'error': str(e)}), 500


# Extraction of Metadata from mzml files

@app.route("/extract/mzml_metadata/json", methods=["POST"])
@app.input(FileMetadata, location='form_and_files')
@app.doc(tags=['FileMetadata:MetadataExtraction'])
def mzml_metadata_extraction(form_and_files_data):
    uploaded_file = form_and_files_data["main_file"]
    if not uploaded_file.filename:
        return jsonify(error="empty filename"), 400

    file_id = foldername()
    filename = secure_filename(uploaded_file.filename)
    metadata_parameter = form_and_files_data["include_parameter"]

    if not filename.lower().endswith('.mzml'):
        return jsonify({'error': 'File is not of mzML extention'}), 400

    print("Incoming Files: \n")
    
    try:
        upload_fileobj(uploaded_file, filename, file_id)
    except ClientError as e:
        return jsonify({'Error Type': str(e)}) , 500

    try:
        download_url = download_file(filename=filename, file_id=file_id)
    except (ClientError,BotoCoreError) as e:
        return jsonify({'Error Type': str(e)}) , 500 
    
    try:
        output_folder_path = os.path.join(working_dir, file_id)
        new_path = fetch_file(url=download_url, filename=filename, folder_id=file_id)
        output_file_name = filename.rsplit(".", 1)[0] + "_metadata.json"
        output_file_path = os.path.join(output_folder_path, output_file_name)

        # label -> kwargs
        META_OPTS = {
            "none":                       {},
            "with spectra":               {"include_spectra": True},
            "with chromatogram":          {"include_chromatograms": True},
            "with spectra+chromatogram":  {"include_spectra": True, "include_chromatograms": True},
        }

        metadata = extract_metadata(new_path, **META_OPTS[metadata_parameter])

        with open(output_file_path, "w", encoding="utf-8") as f:
            for chunk in json.JSONEncoder(indent=2, ensure_ascii=False).iterencode(metadata):
                f.write(chunk) 
        
        with open(output_file_path,'rb') as fh:
            upload_fileobj(fh, output_file_name, file_id)
        download_url = download_file(filename=output_file_name, file_id=file_id)

        remove_folder(output_folder_path)

        payload = {
                "status": "success",
                "process": "Metadata Extraction",
                "file_info": {
                    "filename": output_file_name,
                    "download_url": download_url,
                    "valid_for": "1 hour"
                },
                "meta": {
                    "message": "Metadata Extraction in mzml Schema",
                    "timestamp": datetime.datetime.now(pytz.timezone("Europe/Berlin")).isoformat(),
                    "http_status": 200
                }
            }
        
        return Response(
                json.dumps(payload, indent=2, ensure_ascii=False),
                mimetype="application/json"
            ), 200

    except Exception as e:
        remove_folder(output_folder_path)
        return jsonify({'error': 'Error during Metadata Extraction', 'details': str(e)}), 500


    

# ------------------------------------------------------------------
# CLI entry point
# ------------------------------------------------------------------
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, threaded=True)