from flask import send_file, send_from_directory, jsonify, Response
from apiflask import APIFlask, Schema, abort
from apiflask.fields import Integer, String, File
from apiflask.validators import Length, OneOf
from typing import BinaryIO, Union
from pathlib import Path
# from marshmallow import Schema, fields
from werkzeug.utils import secure_filename
import os
import random, string
from time import sleep
import requests
import datetime
import pytz
import json
import shutil , time
from mzml_metadataextractor.mzml_metadata_extraction import extract_metadata

# from api_scripts.loading_animation import Loader

main_path = os.getcwd()
temp_file_folder = os.path.join(main_path, "input_files")

app = APIFlask(__name__, title='Mass Spectrometry (MS) File Converter', version='1.0', docs_path='/api')

app.config['DESCRIPTION'] = "The objective is to convert MS file into mzML"
app.config['EXTERNAL_DOCS'] = {
    'description': "NFDI4Chem",
    'url': 'https://www.nfdi4chem.de/'
}

app.config['TERMS_OF_SERVICE'] = 'http://localhost:5000'
app.config['LICENSE'] = {
    'name': 'MIT',
    'url': 'https://opensource.org/licenses/MIT'
}

app.config['TAGS'] = [
    {'name': 'msconvert:Conversion',
     'description': 'The aim of conversion is to convert a format to a standardized/agreed format'},
    {'name': 'FileInfo:Validation',
     'description': 'The goal of validation is to Validate the converted format converted by converter service.'},
    {'name': 'FileConvert:Conversion',
     'description': 'The aim of conversion is to test the mzML file'},
    {'name': 'FileMetadata:MetadataExtraction',
     'description': 'The aim of extract metadata from the mzML file'},
]

app.config['IMAGE_FOLDER'] = 'input_files'


class Files_convert(Schema):
    main_file = File(
        required=True,
        metadata={'title': 'The path of the input file (in this case RAW file)',
                  'description': 'The objective is to convert the RAW file to mzML file using Proteowizard-->'
                                 'msconvert software'}
    )
    parameters = String(
        required=False,
        metadata={'title': 'This is for additional parameter that could be added for conversion',
                  'description': 'Additional parameter that can modify the outputs'}
    )
    


class Files_validate(Schema):
    validation_file = File(
        required=False,
        metadata={'title': 'The path of the intermediate file or "validate.yml" file generated by the converter service',
                  'description': 'The path of the intermediate yml file is given'}
    )
   

class Filesconverter(Schema):
    main_file = File(
        required=True,
        metadata={'title': 'The path of the input file (in this case mzML file)',
                  'description': 'The objective is to test the mzML file to FileConvert'}
    )


class FileMetadata(Schema):
    main_file = File(
        required=True,
        metadata={'title': 'The path of the input file (in this case mzML file)',
                  'description': 'The objective is to extract metadata from the mzML.'}
    )
    include_parameter = String(
        required=True,
        validate=OneOf(['none', 'with spectra', 'with chromatogram', 'with spectra+chromatogram']),
        metadata={'description': 'Extra data to attach'}
    )

    

#@app.post('/msconvert_convert')
@app.route('/convert/msconvert', methods = ['POST'])
@app.input(Files_convert, location='form_and_files')
@app.doc(tags=['msconvert:Conversion'])
def raw_conversion(form_and_files_data):
    try:
        if "main_file" not in form_and_files_data:
            return {"error": "No main_file part"}, 400
        file_t = form_and_files_data["main_file"]
        file_parameters = form_and_files_data["parameters"]
        filename = secure_filename(file_t.filename)
        folder_name = random_string_folder_generator()
        print(f"filename: {filename}")
    
        temp_full_path = os.path.join(temp_file_folder, folder_name)
        print(f"full_path: {temp_full_path}")
    
        os.makedirs(temp_full_path, exist_ok=True)
        full_output_filename = os.path.join(temp_full_path,filename)
        file_t.save(os.path.join(temp_full_path, filename))
        
        if filename.lower().endswith(('.tar', '.tar.gz' ,'.tar.xz', '.raw')):
            request1= requests.post(url="http://nfdi4chem-ms-msconvert:4000/msconvert_file",
            json={
                'filename': filename,
                'config': file_parameters,
                'foldername': folder_name
            })
            request1.raise_for_status()
            print(request1.json())
            mzml_name = request1.json()["mzml_outputfile_name"]
            new_temp_file_folder = os.path.join(temp_file_folder, folder_name)
            check = False
            
            for file in os.listdir(new_temp_file_folder):
                if ".mzML" in file:
                    check = True
                    return send_from_directory(new_temp_file_folder, file, as_attachment=True)
            if not check:
                return {'message': 'Failed to convert the file into mzML File',
                'name of file': f'{filename}'
                }
            os.chdir(main_path)
            return {'message': 'Upload Success',
                    'name of file': f'{filename}',
                    'output_filename': mzml_name,
                    "timestamp": datetime.datetime.now(pytz.timezone("Europe/Berlin")).isoformat(),
                    "http_status": request1.status_code

                }
        else:
            return{
                'message': 'Unsupported file extension.'
            }

    except Exception as e:
        # Optionally log the error here
        print("Exception in raw_conversion:", str(e))
        return {'error': 'Internal server error', 'details': str(e)}, 500





    
# Validation of the mzml data

@app.route("/validate/fileinfo", methods=["POST"])
@app.input(Files_validate, location='form_and_files')
#@app.output(FileInfoOut)
@app.doc(tags=['FileInfo:Validation'])
def validation_result(form_and_files_data):
    uploaded_file = form_and_files_data["validation_file"]

    if not uploaded_file.filename:
        return jsonify({'Error Type: Empty File Name Found'}) , 400

    folder_name = random_string_folder_generator()
    filename = secure_filename(uploaded_file.filename)

    input_save_folder_path = os.path.join(temp_file_folder, folder_name)
    uploaded_file.save(os.path.join(input_save_folder_path, filename))

    # FileStorage is already a BinaryIO object; just hand it over.
    # upload_fileobj streams via requests.put, so memory stays low.
    
    try:
        if filename.lower().endswith('mzml'):
            request1= requests.post(url="http://nfdi4chem-ms-validation:3000/fileinfo_mzml",
            json={
                'filename': filename,
                'foldername': folder_name
            })
            request1.raise_for_status()
            print(request1.json())
            payload = {
                "status": "success",
                "file_info": {
                    "filename": filename
                },
                "meta": {
                    "output_message": request1.json()["output_messge"],
                    "timestamp": datetime.datetime.now(pytz.timezone("Europe/Berlin")).isoformat(),
                    "time_taken_for_Validation (sec)": request1.json()["time_taken_sec"],
                    "http_status": request1.status_code
                }
            }
            return Response(
                json.dumps(payload, indent=2, ensure_ascii=False),
                mimetype="application/json"
            ), 200

        else:
            return jsonify({'error': "Error incurred due to File format"}), 500
    except Exception as e:
        return jsonify({'error': str(e)}), 500




# Convert + validation of mzml data

@app.route("/convert/fileconvert", methods=["POST"])
@app.input(Filesconverter, location='form_and_files')
@app.doc(tags=['FileConvert:Conversion'])
def fileconvert(form_and_files_data):
    uploaded_file = form_and_files_data["main_file"]
    if not uploaded_file.filename:
        return jsonify(error="empty filename"), 400

    folder_name = random_string_folder_generator()
    filename = secure_filename(uploaded_file.filename)

    input_save_folder_path = os.path.join(temp_file_folder, folder_name)
    uploaded_file.save(os.path.join(input_save_folder_path, filename))

    
    try:
        if filename.lower().endswith('mzml'):
            request1= requests.post(url="http://nfdi4chem-ms-validation:3000/fileconvert_mzml",
            json={
                'filename': filename,
                'foldername': folder_name
            })
            request1.raise_for_status()
            print(request1.json())

            for file in os.listdir(input_save_folder_path):
                if "_FileConverter_output.mzML" in file:
                    return send_from_directory(input_save_folder_path, file)

        else:
            return jsonify({'error': "Error incurred due to File format"}), 500
    except Exception as e:
        return jsonify({'error': str(e)}), 500


# api for metadata extraction

@app.route("/extraction/mzml_metadata", methods=["POST"])
@app.input(FileMetadata, location='form_and_files')
@app.doc(tags=['FileMetadata:MetadataExtraction'])
def mzml_metadata_extraction(form_and_files_data):
    uploaded_file = form_and_files_data["main_file"]
    if not uploaded_file.filename:
        return jsonify(error="empty filename"), 400

    foldername = random_string_folder_generator()
    filename = secure_filename(uploaded_file.filename)
    metadata_parameter = form_and_files_data["include_parameter"]

    if not filename.lower().endswith('.mzml'):
        return jsonify({'error': 'File is not of mzML extention'}), 400

    print("Incoming Files: \n")
    output_folder_path = os.path.join(temp_file_folder, foldername)
    uploaded_file.save(os.path.join(output_folder_path, filename))
    
    try:
        new_path = os.path.join(output_folder_path, filename)
        
        output_file_name = filename.rsplit(".", 1)[0] + "_metadata.json"
        output_file_path = os.path.join(output_folder_path, output_file_name)
        # label -> kwargs
        META_OPTS = {
            "none":                       {},
            "with spectra":               {"include_spectra": True},
            "with chromatogram":          {"include_chromatograms": True},
            "with spectra+chromatogram":  {"include_spectra": True, "include_chromatograms": True},
        }
        print("Extracting Metadata!!")
        metadata = extract_metadata(Path(new_path), **META_OPTS[metadata_parameter])
        print("Metadata Extracted!!")
        with open(output_file_path, "w", encoding="utf-8") as f:
            for chunk in json.JSONEncoder(indent=2, ensure_ascii=False).iterencode(metadata):
                f.write(chunk) 

        for file in os.listdir(output_folder_path):
                if "_metadata.json" in file:
                    return send_from_directory(output_folder_path, file, as_attachment=True, download_name=output_file_name )
                

    except Exception as e:
        return jsonify({'error': 'Error during Metadata Extraction', 'details': str(e)}), 500
    
    finally:
        delete_old_folder(temp_file_folder)


def random_string_folder_generator():
    random_string= str(''.join(random.choices(string.ascii_lowercase+string.digits,k=8)))
    os.makedirs(os.path.join(temp_file_folder,random_string))
    return random_string


# for deleting old folders
def delete_old_folder(root: Union[Path,str]) -> None:
    """
    Recursively delete every *directory* under `root` whose mtime
    is older than 1 hour.  Files directly under `root` are left untouched.
    """
    root = Path(root)
    if not root.is_dir():
        return

    now = time.time()
    one_hour = 3600  # seconds

    for item in root.iterdir():
        if item.is_dir() and (now - item.stat().st_mtime) > one_hour:
            shutil.rmtree(item, ignore_errors=True)


if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=False)